

import {AdminCounsellor,PlatformSettings, AdminUser, AdminMetrics, CounsellorRequest, Report, AdminAppointment } from "./admin-types"

export const mockAdminUsers: AdminUser[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@university.edu',
    role: 'student',
    status: 'active',
    joinedDate: '2024-01-15',
    lastActive: '2024-03-23',
    avatar: 'SJ',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'mchen@university.edu',
    role: 'student',
    status: 'active',
    joinedDate: '2024-02-10',
    lastActive: '2024-03-24',
    avatar: 'MC',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.r@counselors.com',
    role: 'counsellor',
    status: 'active',
    joinedDate: '2023-11-05',
    lastActive: '2024-03-24',
    avatar: 'ER',
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'jwilson@university.edu',
    role: 'student',
    status: 'suspended',
    joinedDate: '2024-01-20',
    lastActive: '2024-03-10',
    avatar: 'JW',
  },
  {
    id: '5',
    name: 'Dr. Patricia Lee',
    email: 'plee@counselors.com',
    role: 'counsellor',
    status: 'active',
    joinedDate: '2023-10-01',
    lastActive: '2024-03-23',
    avatar: 'PL',
  },
]

export const mockAdminAppointments: AdminAppointment[] = [
  {
    id: 'apt-001',
    studentId: '1',
    studentName: 'Sarah Johnson',
    counsellorId: '3',
    counsellorName: 'Emily Rodriguez',
    scheduledAt: '2024-03-25T14:00:00',
    duration: 45,
    status: 'scheduled',
    mode: 'video',
    reason: 'Stress management and study habits',
  },
  {
    id: 'apt-002',
    studentId: '2',
    studentName: 'Michael Chen',
    counsellorId: '5',
    counsellorName: 'Dr. Patricia Lee',
    scheduledAt: '2024-03-26T10:30:00',
    duration: 60,
    status: 'pending',
    mode: 'text',
    reason: 'Anxiety and social concerns',
  },
  {
    id: 'apt-003',
    studentId: '1',
    studentName: 'Sarah Johnson',
    counsellorId: '3',
    counsellorName: 'Emily Rodriguez',
    scheduledAt: '2024-03-20T15:00:00',
    duration: 45,
    status: 'completed',
    mode: 'video',
    reason: 'Follow-up session',
  },
  {
    id: 'apt-004',
    studentId: '4',
    studentName: 'James Wilson',
    counsellorId: '5',
    counsellorName: 'Dr. Patricia Lee',
    scheduledAt: '2024-03-15T11:00:00',
    duration: 45,
    status: 'cancelled',
    mode: 'phone',
    reason: 'Personal crisis support',
  },
]

export const mockReports: Report[] = [
  {
    id: 'rpt-001',
    reportedBy: '1',
    reportedByName: 'Sarah Johnson',
    againstId: '3',
    againstName: 'Emily Rodriguez',
    reason: 'Unprofessional communication',
    severity: 'high',
    status: 'in_review',
    description:
      'Counsellor was dismissive during our last session and did not provide adequate support for my concerns.',
    appointmentId: 'apt-001',
    createdAt: '2024-03-22',
    updatedAt: '2024-03-23',
    notes: 'Requires immediate review and counsellor feedback.',
  },
  {
    id: 'rpt-002',
    reportedBy: '2',
    reportedByName: 'Michael Chen',
    againstId: '5',
    againstName: 'Dr. Patricia Lee',
    reason: 'Breach of confidentiality',
    severity: 'critical',
    status: 'open',
    description:
      'Counsellor mentioned my personal information to another student. This is a serious violation of privacy.',
    appointmentId: 'apt-002',
    createdAt: '2024-03-24',
    updatedAt: '2024-03-24',
    notes: 'URGENT - Critical severity flag. Contact counsellor immediately.',
  },
  {
    id: 'rpt-003',
    reportedBy: '1',
    reportedByName: 'Sarah Johnson',
    againstId: '3',
    againstName: 'Emily Rodriguez',
    reason: 'Missed appointment',
    severity: 'low',
    status: 'resolved',
    description: 'Counsellor did not show up for scheduled appointment without notice.',
    appointmentId: 'apt-003',
    createdAt: '2024-03-18',
    updatedAt: '2024-03-20',
    resolvedAt: '2024-03-20',
    notes: 'Counsellor provided compensation and rescheduled. Issue resolved.',
  },
  {
    id: 'rpt-004',
    reportedBy: '4',
    reportedByName: 'James Wilson',
    againstId: '5',
    againstName: 'Dr. Patricia Lee',
    reason: 'Inappropriate behavior',
    severity: 'high',
    status: 'open',
    description:
      'During a sensitive discussion, the counsellor made comments that felt inappropriate and made me uncomfortable.',
    appointmentId: 'apt-004',
    createdAt: '2024-03-20',
    updatedAt: '2024-03-20',
  },
]

export const mockCounsellorRequests: CounsellorRequest[] = [
  {
    id: 'req-001',
    name: 'Dr. David Martinez',
    email: 'dmartinez@counseling.com',
    specialization: ['Anxiety', 'Depression', 'Career counselling'],
    yearsExperience: 8,
    bio: 'Licensed therapist with 8 years of experience in student mental health.',
    credentials: ['PhD in Clinical Psychology', 'Licensed Professional Counselor'],
    status: 'pending',
    appliedAt: '2024-03-20',
    avatar: 'DM',
  },
  {
    id: 'req-002',
    name: 'Jessica Park',
    email: 'jpark@wellnesscenters.com',
    specialization: ['Stress Management', 'Mindfulness', 'Sleep Issues'],
    yearsExperience: 5,
    bio: 'Wellness coach specializing in student stress and burnout prevention.',
    credentials: ['Master\'s in Counseling', 'Certified Wellness Coach'],
    status: 'pending',
    appliedAt: '2024-03-22',
    avatar: 'JP',
  },
]

export const mockAdminMetrics: AdminMetrics = {
  totalUsers: 245,
  activeCounsellors: 12,
  pendingApprovals: 2,
  totalAppointments: 487,
  openReports: 3,
  criticalReports: 1,
}

export const mockAdminCounsellors: AdminCounsellor[] = [
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.r@counselors.com',
    specialization: ['Anxiety', 'Depression', 'Stress Management'],
    yearsExperience: 7,
    avatar: 'ER',
    status: 'active',
    rating: 4.8,
    totalSessions: 156,
    completedSessions: 145,
    joinedDate: '2023-11-05',
    bio: 'Licensed therapist specializing in student mental health and anxiety disorders.',
    sessionFee: 45,
    availability: 'available',
    credentials: ['Master\'s in Clinical Psychology', 'Licensed Professional Counselor'],
  },
  {
    id: '5',
    name: 'Dr. Patricia Lee',
    email: 'plee@counselors.com',
    specialization: ['Career Counselling', 'Life Planning', 'Personal Development'],
    yearsExperience: 12,
    avatar: 'PL',
    status: 'active',
    rating: 4.9,
    totalSessions: 289,
    completedSessions: 280,
    joinedDate: '2023-10-01',
    bio: 'Experienced career counselor and life coach with focus on student success and wellbeing.',
    sessionFee: 60,
    availability: 'busy',
    credentials: ['PhD in Counseling Psychology', 'Certified Career Counselor'],
  },
  {
    id: '6',
    name: 'James Thompson',
    email: 'jthompson@counselors.com',
    specialization: ['ADHD Support', 'Learning Disabilities', 'Study Skills'],
    yearsExperience: 9,
    avatar: 'JT',
    status: 'active',
    rating: 4.6,
    totalSessions: 198,
    completedSessions: 190,
    joinedDate: '2023-12-10',
    bio: 'Specialist in academic counseling and neurodiversity support for students.',
    sessionFee: 50,
    availability: 'offline',
    credentials: ['Master\'s in Education Psychology', 'ADHD Coach Certification'],
  },
  {
    id: '7',
    name: 'Dr. Sophia Chen',
    email: 'sophiachen@counselors.com',
    specialization: ['Relationship Issues', 'Communication', 'Social Anxiety'],
    yearsExperience: 10,
    avatar: 'SC',
    status: 'on_leave',
    rating: 4.7,
    totalSessions: 267,
    completedSessions: 260,
    joinedDate: '2023-09-15',
    bio: 'Expert in interpersonal relationships and communication skills development.',
    sessionFee: 55,
    availability: 'offline',
    credentials: ['PhD in Clinical Psychology', 'Marriage and Family Therapist'],
  },
  {
    id: '8',
    name: 'Marcus Johnson',
    email: 'mjohnson@counselors.com',
    specialization: ['Grief Support', 'Crisis Intervention', 'Substance Use'],
    yearsExperience: 14,
    avatar: 'MJ',
    status: 'active',
    rating: 4.9,
    totalSessions: 412,
    completedSessions: 405,
    joinedDate: '2023-08-20',
    bio: 'Crisis intervention specialist with extensive experience in student mental health emergencies.',
    sessionFee: 65,
    availability: 'available',
    credentials: ['Master\'s in Social Work', 'Crisis Intervention Specialist'],
  },
  {
    id: '9',
    name: 'Dr. Amelia Foster',
    email: 'afoster@counselors.com',
    specialization: ['Eating Disorders', 'Body Image', 'Wellness'],
    yearsExperience: 8,
    avatar: 'AF',
    status: 'inactive',
    rating: 4.5,
    totalSessions: 124,
    completedSessions: 120,
    joinedDate: '2024-01-05',
    bio: 'Specialized counselor in eating disorders and body image issues for students.',
    sessionFee: 55,
    availability: 'offline',
    credentials: ['Master\'s in Nutrition and Mental Health', 'Eating Disorder Specialist'],
  },
]

export const mockPlatformSettings: PlatformSettings = {
  appointmentAutoCancelMinutes: 30,
  reminderTimings: {
    oneHourBefore: true,
    tenMinutesBefore: true,
  },
  emailNotifications: {
    newReports: true,
    appointmentReminders: true,
    counsellorRequests: true,
  },
}
